# Site settings
title: 개발자 신동구의 프로필
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings

username: 신동구
user_description: 사용자의 입장에서 생각하는 개발자 신동구 입니다.
user_title: Java & Spring 기반의 backend Engineer
email: ggg9905@naver.com

# linkedin_username: murraco
github_username:  shsh99
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

profile_image: /dog.png

exclude: ['package.json', 'src', 'node_modules', 'vendor']

